name: pharmacy
description: A login Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^3.0.1
  accordion: ^2.1.2
  rxdart: ^0.27.3
  flutter_datetime_picker: ^1.5.1
  extended_image: ^5.1.3
  page_view_indicators: ^2.0.0
  page_transition: ^2.0.4
  flutter_svg: ^0.23.0+1
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  cached_network_image: ^3.1.0+1
  shared_preferences: ^2.0.7
  sqflite: ^2.0.1
  shimmer: ^2.0.0
  geolocator: ^8.0.3
  permission_handler: ^8.3.0

dev_dependencies:


  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

